[[language]]
name = "markdown"
language-servers = ["mdpls"]

[language-server.mdpls]
command = "/home/knee/.cargo/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "floorp" }
