[[language]]
name = "markdown"
language-servers = ["mdpls"]

[[language]]
name = "rhai"
scope = "source.rhai"
file-types = ["rhai"]
language-servers = ["rhai"]

[language-server.mdpls]
command = "/home/knee/.cargo/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "floorp" }

[language-server.rhai]
command = "rhai-lsp"
args = ["lsp", "stdio"]
