format = """[$time](fg) [](fg)$username$hostname[](fg)$directory$git_branch$git_status$nodejs$rust$python$lua$golang$memory_usage$cmd_duration
$custom
$character"""

palette = "default"

[palettes.flexoki_dark]
bg = "#100F0F"
fg = "#CECDC3"
orange = "#DA702C"
yellow = "#D0A215"
green = "#879A39"
red = "#D14D41"
aqua = "#3AA99F"
gray = "#A02F6F"
blue = "#205EA6"
purple = "#5E409D"

[palettes.gruvbox_dark]
bg = "#282828"
fg = "#ebdbb2"
orange = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
red = "#fb4934"
aqua = "#8ec07c"
gray = "#a89984"
blue = "#83a598"
purple = "#d3869b"

[palettes.default]
bg = "black"
fg = "bright-white"
orange = "orange"
yellow = "yellow"
green = "green"
red = "red"
aqua = "aqua"
gray = "gray"
blue = "blue"
purple = "purple"

[username]
# Add a dark background color with padding spaces before and after
style_user = "fg:blue bg:fg"
style_root = "fg:red bold bg:fg"
format = "[ $user]($style)"  # two spaces before and after for pill shape
show_always = true

[hostname]
ssh_only = false
style = "fg:purple bold bg:fg"
format = "[@$hostname ]($style)"  # spaces to pad the pill shape
disabled = false


[directory]
style = "fg:green bold"
read_only = " 󰌾"
truncation_length = 3
truncate_to_repo = false
format = "[ $path]($style)[$read_only](fg:red) "

[git_branch]
symbol = "󰘬 "
style = "fg:orange bold"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:aqua"
conflicted = "󰅙 "
ahead = "󰜷 ${count} "
behind = "󰜮 ${count} "
diverged = "󰹺 ${ahead_count}󰜮 ${behind_count} "
untracked = "󰋗 ${count} "
stashed = "󰏗 ${count} "
modified = "󰏫 ${count} "
staged = "󰐗 ${count} "
renamed = "󰑕 ${count} "
deleted = "󰍴 ${count} "

[nodejs]
symbol = "󰎙 "
style = "fg:green bold"
format = "[$symbol$version]($style) "

[rust]
symbol = "󱘗 "
style = "fg:red bold"
format = "[$symbol$version]($style) "

[python]
symbol = "󰌠 "
style = "fg:yellow bold"
format = "[$symbol$version]($style) "

[lua]
symbol = "󰢱 "
style = "fg:blue bold"
format = "[$symbol$version]($style) "

[golang]
symbol = "󰟓 "
style = "fg:aqua bold"
format = "[$symbol$version]($style) "

[time]
disabled = false
time_format = "%I:%M %p"
style = "fg:yellow italic"
format = "[$time]($style)"

[custom.uptime]
command = "uptime -p | sed 's/up //'"
when = "true"
style = "fg:gray italic"
format = "[$output]($style)"

[character]
success_symbol = "[ ●](bold green)"
error_symbol = "[ ●](bold red)"
vimcmd_symbol = "[ ●](bold yellow)"
