#!/bin/bash

notify() {
  notify-send "Monitor Toggle" "$@"
}

# Get current_mode for DP-1
current_mode=$(niri msg --json outputs | jq -r '.["DP-1"].current_mode')

case "$current_mode" in
  null)
    echo "Turning on DP-1 monitor..."
    niri msg output DP-1 on
    ddcutil --bus=6 setvcp 0x60 0x09
    xrandr --output DP-1 --primary
    sleep 3
    notify "DP-1 monitor enabled and set as primary"
    ;;
  *)
    echo "Turning off DP-1 monitor..."
    niri msg output DP-1 off
    ddcutil --bus=6 setvcp 0x60 0x06
    sleep 3
    notify "DP-1 monitor disabled"
    ;;
esac
